ARG from
FROM ${from} as base-conda
LABEL org.opencontainers.image.authors="armando.ucf@gmail.com"

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]
#ENV TZ=UTC
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#ARG uname=ezdev
#ARG gname=ezdev

FROM base-conda as base-ai

ARG venv="base"
ARG activate="source /root/.bashrc \
      && mamba activate ${venv} && umask 0000"

# pytorch has cuda added
RUN mkdir -p /root/pyenv
COPY pyenv/pytorch.yml /root/pyenv/
RUN ${activate} && mamba env update -n ${venv} --file /root/pyenv/pytorch.yml
COPY pyenv/tensorflow.yml /root/pyenv/
RUN ${activate} && mamba env update -n ${venv} --file /root/pyenv/tensorflow.yml
COPY pyenv/ai-core.yml /root/pyenv/
RUN ${activate} && mamba env update -n ${venv} --file /root/pyenv/ai-core.yml
COPY pyenv/ai-lm.yml /root/pyenv/
RUN ${activate} && mamba env update -n ${venv} --file /root/pyenv/ai-lm.yml
COPY pyenv/ai-lm-pip.yml /root/pyenv/
RUN ${activate} && mamba env update -n ${venv} --file /root/pyenv/ai-lm-pip.yml

RUN ${activate} && mamba clean -itcly

RUN rm -rf /root/pyenv

FROM base-conda as ai

COPY --from=base-ai /opt/py /opt/py
COPY container-scripts/entrypoint.d/ezdev/22-jupyter.sh /opt/container-scripts/entrypoint.d/ezdev/
#USER root
#COPY container-scripts/jupyter-lab.service /etc/systemd/system/
#RUN sudo systemctl daemon-reload
#RUN sudo systemctl enable jupyter-lab


#ENTRYPOINT ["/opt/container-scripts/entrypoint.sh"]
#CMD ["bash"]
