name: Build Docker Images

on:
  workflow_dispatch
    
#  push:
#    branches:
#      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Login to GitLab
      #  uses: docker/login-action@v2
      #  with:
      #    registry: registry.gitlab.com
      #    username: ${{ secrets.GITLAB_USERNAME }}
      #    password: ${{ secrets.GITLAB_PASSWORD }}

      #- name: Extract metadata (tags, labels) for Docker
      #  id: meta
      #  uses: docker/metadata-action@v4
      #  with:
      #    images: |
      #      ghcr.io/${{ github.repository }}


      #- name: Build the base image
      #  run: docker compose build base

      #- name: Push the base image
      #  run: docker compose push base

      - name: Build and push base
        uses: docker/bake-action@v3
        with:
          files: docker-compose.yml
          targets: base, conda, ai
          push: true
