name: Build Docker Images

on:
  workflow_dispatch
    
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build the base image
        run: docker compose build base
      - name: Push the base image
        run: docker compose push base


